name: Build & Deploy iOS App
on:
  push:
    paths:
      - .github/workflows/build_n.yml

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Build iOS App
        run: |
          xcodebuild -workspace CICDAutomate.xcworkspace -scheme CICDAutomate -configuration Release -archivePath $HOME/build/CICDAutomate.xcarchive clean archive -allowProvisioningUpdates

      - name: Find IPA file
        id: find_ipa
        run: |
          echo "Searching for IPA files in $HOME/Library/Developer/Xcode/DerivedData"
          IPA_PATH=$(find $HOME/Library/Developer/Xcode/DerivedData -name '*.ipa' | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "No IPA file found"
            exit 1
          fi
          echo "Found IPA file at: $IPA_PATH"
          echo "::set-output name=ipa_path::$IPA_PATH"

      - name: Upload IPA to Release
        run: |
          gh release upload v1.2.27 ${{ steps.find_ipa.outputs.ipa_path }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
