name: iOS Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          gem install cocoapods
          pod install

#      - name: Build
#        run: |
#          xcodebuild clean build -workspace CICDAutomate.xcworkspace -scheme CICDAutomate -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max'

      - name: Build
        run: |
          xcodebuild clean build -workspace CICDAutomate.xcworkspace -scheme CICDAutomate -destination 'platform=iOS Simulator,name=Any iOS Simulator Device'

      - name: Archive
        run: |
          xcodebuild archive -workspace CICDAutomate.xcworkspace -scheme CICDAutomate -archivePath build/CICDAutomate.xcarchive

      - name: Export archive
        run: |
          xcodebuild -exportArchive -archivePath build/CICDAutomate.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build
