name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          gem install cocoapods
          pod install

      - name: Build
        run: |
          xcodebuild clean build -workspace YourProject.xcworkspace -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 13'

      - name: Archive
        run: |
          xcodebuild archive -workspace YourProject.xcworkspace -scheme YourScheme -archivePath build/YourApp.xcarchive

      - name: Export archive
        run: |
          xcodebuild -exportArchive -archivePath build/YourApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build
